// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poliza.Entities;

#nullable disable

namespace Poliza.Migrations
{
    [DbContext(typeof(PolizaDbContext))]
    partial class PolizaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Entities.PersonaEntity", b =>
                {
                    b.Property<string>("CedulaAsegurado")
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(1)
                        .HasComment("Cédula del asegurado de la persona");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("BIT")
                        .HasColumnOrder(7)
                        .HasComment("Indicador de borrado lógico");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(6)
                        .HasComment("Fecha de nacimiento de la persona");

                    b.Property<Guid>("IdTipoPersona")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(5)
                        .HasComment("Identificador de la persona con la que se relaciona la persona");

                    b.Property<string>("Nombre")
                        .HasMaxLength(512)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2)
                        .HasComment("Nombre de la persona");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(3)
                        .HasComment("Primer apellido de la persona");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(4)
                        .HasComment("Segundo apellido de la persona");

                    b.HasKey("CedulaAsegurado");

                    b.HasIndex("IdTipoPersona")
                        .IsUnique();

                    b.HasIndex(new[] { "EstaEliminado" }, "EstaEliminadoIndex");

                    b.HasIndex(new[] { "IdTipoPersona" }, "IdTipoPersonaIndex");

                    b.HasIndex(new[] { "Nombre" }, "NombreIndex");

                    b.HasIndex(new[] { "CedulaAsegurado" }, "PersonaIndex")
                        .IsUnique();

                    b.HasIndex(new[] { "PrimerApellido" }, "PrimerApellidoIndex");

                    b.HasIndex(new[] { "SegundoApellido" }, "SegundoApellidoIndex");

                    b.ToTable("PersonaTable", "Persona");
                });

            modelBuilder.Entity("Common.Entities.PolizaCoberturaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(1)
                        .HasComment("Identificador del tipo de póliza");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2)
                        .HasComment("Descripción de la cobertura");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("BIT")
                        .HasColumnOrder(3)
                        .HasComment("Indicador de borrado lógico");

                    b.HasKey("Id")
                        .HasName("PK_PolizaCobertura_Id");

                    b.HasIndex(new[] { "Descripcion", "EstaEliminado" }, "TipoPolizaBusquedaIndex")
                        .IsUnique()
                        .HasFilter("[Descripcion] IS NOT NULL");

                    b.HasIndex(new[] { "Id" }, "TipoPolizaIndex")
                        .IsUnique();

                    b.ToTable("PolizaCoberturaTable", "PolizaSchema");
                });

            modelBuilder.Entity("Common.Entities.PolizaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(1)
                        .HasComment("Identificador de la póliza");

                    b.Property<string>("Aseguradora")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(13)
                        .HasComment("Nombre de la aseguradora");

                    b.Property<string>("CedulaAsegurado")
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(4)
                        .HasComment("Cédula del asegurado");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("BIT")
                        .HasColumnOrder(14)
                        .HasComment("Indicador de borrado lógico");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(7)
                        .HasComment("Fecha de emisión de la póliza");

                    b.Property<DateTime>("FechaInclusion")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(12)
                        .HasComment("Fecha de inclusión de la póliza");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(6)
                        .HasComment("Fecha de vencimiento de la póliza");

                    b.Property<Guid>("IdCobertura")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(8)
                        .HasComment("Coberturas de la póliza");

                    b.Property<Guid>("IdPolizaEstado")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(9)
                        .HasComment("Identificador del estado de la póliza");

                    b.Property<Guid>("IdTipoPoliza")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(3)
                        .HasComment("Identificador del tipo de póliza");

                    b.Property<decimal>("MontoAsegurado")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnOrder(5)
                        .HasComment("Monto asegurado");

                    b.Property<string>("NumeroPoliza")
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2)
                        .HasComment("Número de póliza");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(11)
                        .HasComment("Periodo de cobertura de la póliza");

                    b.Property<decimal>("Prima")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnOrder(10)
                        .HasComment("Prima de la póliza");

                    b.HasKey("Id")
                        .HasName("PK_Poliza_Id");

                    b.HasIndex("CedulaAsegurado")
                        .IsUnique()
                        .HasFilter("[CedulaAsegurado] IS NOT NULL");

                    b.HasIndex("IdCobertura")
                        .IsUnique();

                    b.HasIndex("IdPolizaEstado")
                        .IsUnique();

                    b.HasIndex("IdTipoPoliza")
                        .IsUnique();

                    b.HasIndex(new[] { "CedulaAsegurado" }, "PolizaCedulaAseguradoIndex");

                    b.HasIndex(new[] { "FechaVencimiento" }, "PolizaFechaVencimientoIndex");

                    b.HasIndex(new[] { "IdTipoPoliza" }, "PolizaIdTipoPolizaIndex");

                    b.HasIndex(new[] { "NumeroPoliza" }, "PolizaNumeroPolizaIndex");

                    b.ToTable("PolizaTable", "PolizaSchema");
                });

            modelBuilder.Entity("Common.Entities.PolizaEstadoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(1)
                        .HasComment("Identificador del estado de la póliza");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2)
                        .HasComment("Descripción del estado de la póliza");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("BIT")
                        .HasColumnOrder(3)
                        .HasComment("Indicador de borrado lógico");

                    b.HasKey("Id")
                        .HasName("PK_PolizaEstado_Id");

                    b.HasIndex(new[] { "Descripcion", "EstaEliminado" }, "TipoPolizaBusquedaIndex")
                        .IsUnique()
                        .HasFilter("[Descripcion] IS NOT NULL");

                    b.HasIndex(new[] { "Id" }, "TipoPolizaIndex")
                        .IsUnique();

                    b.ToTable("PolizaEstadoTable", "PolizaSchema");
                });

            modelBuilder.Entity("Common.Entities.TipoPersonaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(1)
                        .HasComment("Identificador del catálogo de tipo de persona");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("BIT")
                        .HasColumnOrder(3)
                        .HasComment("Indicador de borrado lógico");

                    b.Property<string>("TipoPersona")
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2)
                        .HasComment("Tipo de persona");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "TipoPersonaIndex")
                        .IsUnique();

                    b.ToTable("TipoPersonaTable", "Persona");
                });

            modelBuilder.Entity("Common.Entities.TipoPolizaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(1)
                        .HasComment("Identificador del tipo de póliza");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(512)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2)
                        .HasComment("Descripción del tipo de póliza");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("BIT")
                        .HasColumnOrder(3)
                        .HasComment("Indicador de borrado lógico");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Descripcion", "EstaEliminado" }, "TipoPolizaBusquedaIndex")
                        .IsUnique()
                        .HasFilter("[Descripcion] IS NOT NULL");

                    b.HasIndex(new[] { "Id" }, "TipoPolizaIndex")
                        .IsUnique();

                    b.ToTable("TipoPoliza", "PolizaSchema");
                });

            modelBuilder.Entity("Common.Entities.PersonaEntity", b =>
                {
                    b.HasOne("Common.Entities.TipoPersonaEntity", "TipoPersona")
                        .WithOne("Persona")
                        .HasForeignKey("Common.Entities.PersonaEntity", "IdTipoPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPersona");
                });

            modelBuilder.Entity("Common.Entities.PolizaEntity", b =>
                {
                    b.HasOne("Common.Entities.PersonaEntity", "Persona")
                        .WithOne("Poliza")
                        .HasForeignKey("Common.Entities.PolizaEntity", "CedulaAsegurado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Poliza_Persona");

                    b.HasOne("Common.Entities.PolizaCoberturaEntity", "PolizaCobertura")
                        .WithOne("PolizaEntity")
                        .HasForeignKey("Common.Entities.PolizaEntity", "IdCobertura")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Poliza_PolizaCobertura");

                    b.HasOne("Common.Entities.PolizaEstadoEntity", "PolizaEstado")
                        .WithOne("PolizaEntity")
                        .HasForeignKey("Common.Entities.PolizaEntity", "IdPolizaEstado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Poliza_PolizaEstado");

                    b.HasOne("Common.Entities.TipoPolizaEntity", "TipoPoliza")
                        .WithOne("PolizaEntity")
                        .HasForeignKey("Common.Entities.PolizaEntity", "IdTipoPoliza")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Poliza_TipoPoliza");

                    b.Navigation("Persona");

                    b.Navigation("PolizaCobertura");

                    b.Navigation("PolizaEstado");

                    b.Navigation("TipoPoliza");
                });

            modelBuilder.Entity("Common.Entities.PersonaEntity", b =>
                {
                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("Common.Entities.PolizaCoberturaEntity", b =>
                {
                    b.Navigation("PolizaEntity");
                });

            modelBuilder.Entity("Common.Entities.PolizaEstadoEntity", b =>
                {
                    b.Navigation("PolizaEntity");
                });

            modelBuilder.Entity("Common.Entities.TipoPersonaEntity", b =>
                {
                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Common.Entities.TipoPolizaEntity", b =>
                {
                    b.Navigation("PolizaEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
